### PR TITLE
Failing build

### PR DESCRIPTION
**Pull request by ruudk**
See https://github.com/shivammathur/setup-php/issues/423

### CODE REVIEW

**Comment by shivammathur** [comment]
Add pull_request to the yml
```diff
 name: Test
 on:
   push:
+  pull_request:
 jobs:
 ```

**Comment by shivammathur** [comment]
It does not support 8.1, so remove that and run with `fail-fast: false` in matrix

**Comment by ruudk** [comment]
I'm unable to reproduce it, with the exact same config. 

Could it be that my current PR's have it cached somehow?

**Comment by shivammathur** [comment]
There is no cache in the test workflow.
It is pre-installed on the ubuntu images, and should be enabled by default.
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/php.sh#L74

**Comment by ruudk** [comment]
Actions are not kicking off anymore :(

**Comment by shivammathur** [comment]
I found the issue, it is not working on images deployed yesterday

**Comment by ruudk** [comment]
Oke let's move this to https://github.com/shivammathur/setup-php/issues/423 again

**Pull request closed without merging**
